# Site settings
title: MathJax
email: info@mathjax.org
description: "Beautiful math in all browsers."
baseurl: "/MathJax-website/"
# url: "http://www.mathjax.org"
TimeZone: America/New_York

# Build settings
markdown: kramdown
permalink: /:title/
